"""create ivs table

Revision ID: 29bb4bd50fc6
Revises: 
Create Date: 2026-08-17 19:17:18.405393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bb4bd50fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ivs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('track_model_path', sa.String(length=500), nullable=False),
    sa.Column('track_model_confidence', sa.Float(), nullable=False),
    sa.Column('track_model_threshold', sa.Float(), nullable=False),
    sa.Column('defect_model_path', sa.String(length=500), nullable=False),
    sa.Column('defect_model_confidence', sa.Float(), nullable=False),
    sa.Column('defect_model_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ivs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ivs')
    # ### end Alembic commands ###
